### ISSUE TITLE
[BUG] VPM cannot find supported editor for 2022.3.6f1 on Linux

### ISSUE THREAD

**Issue by Foxcapades** [vrchat-community/creator-companion#408]
### Describe the bug

**NOTE** This is a new behavior as of `0.1.21` and persists in `0.1.22`.

When executing VPM it does not use the editor as configured in the `settings.json` file.  Instead, when executed it throws this error:
```console
[14:27:43 INF] Found No Supported Editors
[14:27:43 INF] Unity is not installed.
[14:27:43 ERR] No Unity Editor found, you need to set this before you can make new projects.
```

Additionally, during execution it modifies the `settings.json` file and removes the value set to the `pathToUnityExe` key.

### To Reproduce

1. Install VPM
```console
$ dotnet tool install --global vrchat.vpm.cli
Tool 'vrchat.vpm.cli' was installed with the latest stable version (version '0.1.22').
```

2. Configure `~/.local/share/VRChatCreatorCompanion/settings.json`
```json
  1 {
  2   "pathToUnityExe": "/home/ellie/Unity/Hub/Editor/2022.3.6f1/Editor/Unity",
  3   "pathToUnityHub": "/opt/unityhub/unityhub",
```

3. Execute `vpm new`.
```console
$ vpm new Zoe.1 Avatar -p $PWD 
[14:27:43 INF] Found No Supported Editors
[14:27:43 INF] Unity is not installed.
[14:27:43 ERR] No Unity Editor found, you need to set this before you can make new projects.
```

### Expected behavior

```console
$ vpm new Zoe.1 Avatar -p $PWD
[14:36:31 INF] VPM Doesn't know how to look at Linux executables for version yet, so just returning true for PathIsValidUnityVersion(/home/ellie/Unity/Hub/Editor/2022.3.6f1/Editor/Unity)
[14:36:31 INF] VPM Doesn't know how to look at Linux executables for version yet, so just returning true for PathIsValidUnityVersion(/home/ellie/Unity/Hub/Editor/2022.3.6f1/Editor/Unity)
[14:36:31 INF] Unity is installed.
[14:36:31 INF] Let's create a project named Zoe.1 from the template /home/ellie/.local/share/VRChatCreatorCompanion/VRCTemplates/Avatar at the path /media/ellie/Ashley/3D/Projects/Unity/Zoe.1
[14:36:31 INF] Looking for Legacy Packages to Upgrade by Scanning Folders within com.vrchat.avatars
[14:36:31 INF] Looking for Legacy Packages to Upgrade by Scanning Folders within com.vrchat.avatars
[14:36:31 INF] Looking for Legacy Packages to Upgrade by Scanning Folders within com.vrchat.base
[14:36:31 INF] Resolved package com.vrchat.avatars ^3.5.x
[14:36:31 INF] Resolved all VPM Packages in /media/ellie/Ashley/3D/Projects/Unity/Zoe.1
[14:36:32 INF] Looking for Legacy Packages to Upgrade by Scanning Folders within com.vrchat.core.vpm-resolver
[14:36:32 INF] Looking for Legacy Packages to Upgrade by Scanning Folders within com.vrchat.core.vpm-resolver
[14:36:32 INF] Successfully resolved packages for new Project.
[14:36:32 INF] Project created!
```

(This output is tweaked from the `0.1.20` output to say `^3.5.x` instead of `^3.4.x`)

### Screenshots

**Before execution**
![before](https://github.com/vrchat-community/creator-companion/assets/1297911/7982bae7-75c3-4d28-afd6-08580be3a59f)

**After execution**
![after](https://github.com/vrchat-community/creator-companion/assets/1297911/60397cf1-bfcd-4467-8df2-19add4337742)

### Related Product

VPM CLI

### Product Version

0.1.21, 0.1.22

### OS

macOS / Linux

### Additional context

The workaround I have for now is:

1. stick with version `0.1.20`
2. create a project with `vpm`
3. delete the `./Packages/com.vrchat.*` directories from the project folder (as the older vpm installs outdated packages by default for some reason?)
4. `cd` into the project root directory
5. run `vpm resolve project` to install the correct versions of the packages
6. manually add the new project to Unity Hub
7. open the project in the 2022.3.6f1 version of Unity, hitting "Continue" when it warns about opening the project in a different version of Unity than it was created for.

**Comment by valentinegb** [comment]
Having this same issue on Mac. How do you rollback versions? I already updated to 0.1.22 .-.

**Comment by anatawa12** [comment]
Might be related to #28 

In #28, Setting `pathToUnityExe` was the workaround so I think Setting `preferredUnityEditors` might work as workaround.

**Comment by valentinegb** [comment]
Setting `pathToUnityExe` isn't working since it gets cleared again every time VPM is run, `preferredUnityEditors` I'm not really sure what I would set it to since it looks like it's supposed to be an object.

**Comment by Foxcapades** [comment]
> Having this same issue on Mac. How do you rollback versions? I already updated to 0.1.22 .-.

What I did was:
```
dotnet tool uninstall --global vrchat.vpm.cli
dotnet tool install --global vrchat.vpm.cli --version 0.1.20
````

**Comment by anatawa12** [comment]
For `preferredUnityEditors`, You should set like this I think.
```
  "preferredUnityEditors": {
    "2019": "/Path/To/Unity2019",
    "2022": "/Path/To/Unity2022"
  },
```
I copied partially from settings.json on the windows.

**Comment by valentinegb** [comment]
Same issue :T
(Here's what I have, just in case I'm putting a bad path:)
```json
"preferredUnityEditors": {
  "2022": "/Applications/Unity/Hub/Editor/2022.3.6f1/Unity.app/Contents/MacOS/Unity"
},
```

**Comment by founta** [comment]
I have the same issue for the 2019 unity editor, with it overwriting the `pathToUnityExe` when running vpm. The docs (https://vcc.docs.vrchat.com/vpm/cli/#check-hub) say that it runs this command for vpm check unity:

`unityhub -- --headless editors -i`

but the correct command for linux is this:
`unityhub --headless editors -i`

when running vpm check unity, it appears as if it runs the first command there, as it causes the hub to start up if it is not already running (and that's what happens if you manually run it in a terminal). they must have changed things so that it overwrites the path to the unity executable in those two newer vpm versions

in the old 0.1.20 version, it also cannot find the unity editor due to the above issue, but it does not wipe out that variable in the settings JSON file

**Comment by founta** [comment]
welp, downgrading to 0.1.20 did not help for me and I was probably spouting nonsense in the post above. It still wipes out that path to unity exe when I try to make a new project :(

**Comment by valentinegb** [comment]
The command on macOS is `"./Unity Hub" -- --headless editors -i`, for those wondering. On my Mac, the Unity Hub executable is located at `/Applications/Unity Hub.app/Contents/MacOS`.

**Comment by anatawa12** [comment]
I found that there are unity configuration in litedb file. it might be work well to add unity version to litedb?

**Comment by Livb-VRC** [comment]
Tried downgrading to 1.20 and updating pathToUnityExe, same issue

  "pathToUnityExe": "/Applications/Unity/Hub/Editor/2022.3.6f1/Unity.app/Contents/MacOS/Unity",

**Comment by Robotex** [comment]
Any solution yet?

**Comment by anatawa12** [comment]
I found the solution for this problem but this is extremely tricky solution.

Adding your unity editor to `${XDG_DATA_HOME}/VRChatCreatorCompanion/vcc.liteDb`(or`${HOME}/.local/share/VRChatCreatorCompanion/vcc.liteDb`) will fix this problem.

The following C# code is used with LiteDB 5.0.17 from nuget to fix in my vcc.litedb. If you're familiar with C#, you can fix with this code.

```cs

// Edit FOLLOWING TWO LINES
// IF you don't have installed the unity version, set null to the variable.
var unity2019 = "/Applications/Unity/Hub/Editor/2019.4.31f1/Unity.app/Contents/MacOS/Unity";
var unity2022 = "/Applications/Unity/Hub/Editor/2022.3.6f1/Unity.app/Contents/MacOS/Unity";
// END OF EDIT AREA

var dataHome = Environment.GetEnvironmentVariable("XDG_DATA_HOME")
    ?? Environment.GetEnvironmentVariable("HOME") + "/.local/share";

var connect = new ConnectionString(dataHome + "/VRChatCreatorCompanion/vcc.liteDb");

using (var db = new LiteDatabase(connect))
{
    if (unity2022 != null)
    {
        db.GetCollection("unityVersions").Insert(new BsonDocument()
        {
            { "Path", unity2022 },
            { "Version", "2022.3.6f1" },
            { "LoadedFromHub", false }
        });
    }
    
    if (unity2019 != null)
    {
        db.GetCollection("unityVersions").Insert(new BsonDocument()
        {
            { "Path", unity2019 },
            { "Version", "2019.4.31f1" },
            { "LoadedFromHub", false }
        });
    }
}
```

**Comment by Robotex** [comment]
> I found the solution for this problem but this is extremely tricky solution.
> 
> Adding your unity editor to `${XDG_DATA_HOME}/VRChatCreatorCompanion/vcc.liteDb`(or`${HOME}/.local/share/VRChatCreatorCompanion/vcc.liteDb`) will fix this problem.
> 
> The following C# code is used with LiteDB 5.0.17 from nuget to fix in my vcc.litedb. If you're familiar with C#, you can fix with this code.
> 
> ```cs
> // Edit FOLLOWING TWO LINES
> // IF you don't have installed the unity version, set null to the variable.
> var unity2019 = "/Applications/Unity/Hub/Editor/2019.4.31f1/Unity.app/Contents/MacOS/Unity";
> var unity2022 = "/Applications/Unity/Hub/Editor/2022.3.6f1/Unity.app/Contents/MacOS/Unity";
> // END OF EDIT AREA
> 
> var dataHome = Environment.GetEnvironmentVariable("XDG_DATA_HOME")
>     ?? Environment.GetEnvironmentVariable("HOME") + "/.local/share";
> 
> var connect = new ConnectionString(dataHome + "/VRChatCreatorCompanion/vcc.liteDb");
> 
> using (var db = new LiteDatabase(connect))
> {
>     if (unity2022 != null)
>     {
>         db.GetCollection("unityVersions").Insert(new BsonDocument()
>         {
>             { "Path", unity2022 },
>             { "Version", "2022.3.6f1" },
>             { "LoadedFromHub", false }
>         });
>     }
>     
>     if (unity2019 != null)
>     {
>         db.GetCollection("unityVersions").Insert(new BsonDocument()
>         {
>             { "Path", unity2019 },
>             { "Version", "2019.4.31f1" },
>             { "LoadedFromHub", false }
>         });
>     }
> }
> ```

I initially thought that .liteDb file was empty because OneBella couldn't read it but after running your script Unity was finally recognized in `vpm check unity`. Ty!

**Comment by chemicalcrux** [comment]
I ran into this problem. anatawa12's solution worked for me!

I was very unfamiliar with working with C# outside of Unity projects, so here's how I got that running:

- `dotnet new console`
- `dotnet add LiteDB`
- replace the contents of Program.cs with that script
- `dotnet run`

It initially did not work because I had already downgraded to VPM 0.1.20

Things look fine after upgrading back to 0.1.25

**Comment by anatawa12** [comment]
> I ran into this problem. anatawa12's solution worked for me!
> 
> I was very unfamiliar with working with C# outside of Unity projects, so here's how I got that running:
> 
>     * `dotnet new console`
> 
>     * `dotnet add package LiteDB`
> 
>     * replace the contents of Program.cs with that script; add `using LiteDB;` up top
> 
>     * `dotnet run`
> 
> 
> It initially did not work because I had already downgraded to VPM 0.1.20
> 
> Things look fine after upgrading back to 0.1.25

Sorry I did not include details steps for running the code because it was to show solution looks like.

The steps is correct and sorry for lack of information to do my solution.

**Comment by orels1** [comment]
Hey!
Sorry to hear that is still an issue.
There is an extra mechanism of backwards-compatible syncing of settings into the database.

You can add your absolute editor paths into the `unityEditors` array of your `settings.json` and then run a command like `vpm list projects` or `vpm list unity`. This should insert w/e is in the `unityEditors` array into the database, which in turn should allow the `vpm check unity` to pass.

Just as a bit of extra info - `vpm list unity` always enforces an editor re-scan.

If you could then share the log file when doing that - that could help us diagnose where the issue is.

**Comment by BlackthornYugen** [comment]
> You can add your absolute editor paths into the `unityEditors` array of your `settings.json` and then run a command like `vpm list projects` or `vpm list unity`. This should insert w/e is in the `unityEditors` array into the database, which in turn should allow the `vpm check unity` to pass.

This doesn't seem to fix  `vpm check unity` for me:

```shell
$ file /Applications/Unity/Unity.app/Contents/MacOS/Unity                                                                     
/Applications/Unity/Unity.app/Contents/MacOS/Unity: Mach-O 64-bit executable arm64

$ jq '{pathToUnityExe, pathToUnityHub, preferredUnityEditors}' ~/.local/share/VRChatCreatorCompanion/settings.json
{
  "pathToUnityExe": "/Applications/Unity/Unity.app/Contents/MacOS/Unity",
  "pathToUnityHub": "/Applications/Unity Hub.app/Contents/MacOS/Unity Hub",
  "preferredUnityEditors": {
    "2022": "/Applications/Unity/Unity.app/Contents/MacOS/Unity"
  }
}

$ vpm list unity                                                                                                              
[15:29:53 INF] Found No Supported Editors
[15:29:53 INF] Found 0 Unity Installations.

╭──────────────────────┬─────────────────────────────────────────────────────────────────╮
│ Path                 │ Unity Version                                                   │
╰──────────────────────┴─────────────────────────────────────────────────────────────────╯

$ jq '{pathToUnityExe, pathToUnityHub, preferredUnityEditors}' ~/.local/share/VRChatCreatorCompanion/settings.json
{
  "pathToUnityExe": "",
  "pathToUnityHub": "/Applications/Unity Hub.app/Contents/MacOS/Unity Hub",
  "preferredUnityEditors": {}
}

$ vpm check unity
[15:32:55 INF] Found No Supported Editors
[15:32:55 INF] Unity is not installed.

$ '/Applications/Unity Hub.app/Contents/MacOS/Unity Hub' -- --headless editors -i
2024-07-21 15:23:28.433 Unity Hub[98570:6168891] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
2022.3.22f1 (Apple silicon), installed at /Applications/Unity/Unity.app

$ vpm new coffeetime World 
[15:27:00 INF] Found No Supported Editors
[15:27:00 INF] Unity is not installed.
[15:27:00 ERR] No Unity Editor found, you need to set this before you can make new projects.
```

**Comment by orels1** [comment]
@BlackthornYugen awesome, thanks for confirming!

We also just released a new version of VPM CLI `0.1.26` that increases the timeout for Unity Hub scanning, which seems to be a common underlying issue on macOS and possibly Linux.

If anyone in this thread can try it out and see if this addresses the issue - that would be appreciated.

**Comment by BlackthornYugen** [comment]
@orels1 before I try the updated version, I want to reproduce it on the current version, but I can't seem to get it to fail again. Clearing out the unity path from `settings.json` doesn't seem to break it now. 

```shell
$ time vpm list unity                                                                 
[21:49:20 INF] Found 1 Unity Installations.

╭───────────────────┬─────────────────────────────────────────────────────────────────────────────╮
│ Path              │ Unity Version                                                               │
├───────────────────┼─────────────────────────────────────────────────────────────────────────────┤
│ 2022.3.22f1       │ /Applications/Unity/Unity.app/Contents/MacOS/Unity                          │
╰───────────────────┴─────────────────────────────────────────────────────────────────────────────╯
vpm list unity  0.45s user 0.05s system 9% cpu 5.483 total
$ time '/Applications/Unity Hub.app/Contents/MacOS/Unity Hub' -- --headless editors -i
2024-07-22 21:49:27.653 Unity Hub[9540:7249579] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
2022.3.22f1 (Apple silicon), installed at /Applications/Unity/Unity.app
'/Applications/Unity Hub.app/Contents/MacOS/Unity Hub' -- --headless editors   10.09s user 1.40s system 81% cpu 14.073 total
$ time vpm list unity                                                                 
[21:49:59 INF] Found 1 Unity Installations.

╭───────────────────┬─────────────────────────────────────────────────────────────────────────────╮
│ Path              │ Unity Version                                                               │
├───────────────────┼─────────────────────────────────────────────────────────────────────────────┤
│ 2022.3.22f1       │ /Applications/Unity/Unity.app/Contents/MacOS/Unity                          │
╰───────────────────┴─────────────────────────────────────────────────────────────────────────────╯
vpm list unity  0.44s user 0.07s system 9% cpu 5.475 total
$ time '/Applications/Unity Hub.app/Contents/MacOS/Unity Hub' -- --headless editors -i
2024-07-22 21:50:06.028 Unity Hub[9913:7251716] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
2022.3.22f1 (Apple silicon), installed at /Applications/Unity/Unity.app
'/Applications/Unity Hub.app/Contents/MacOS/Unity Hub' -- --headless editors   9.57s user 1.13s system 76% cpu 13.925 total
```

Does vpm cache the known install paths in `vcc.liteDb`?

**Comment by orels1** [comment]
@BlackthornYugen yes, `vcc.liteDb` stores information about the unity editors. The list in `settings.json` is more for legacy compatibility (since that was added prior to LiteDB backend).

you can renamed it to something like `vcc_old.liteDb` if you just want to test.
Otherwise - you should be able to open the file with something like [OneBella](https://github.com/namigop/OneBella) and remove the `unityVersions` table

It stores some extra metadata for each unity version which is accessed frequently
![image](https://github.com/user-attachments/assets/7ae33181-1548-4923-aa64-477921541a87)

**Comment by BlackthornYugen** [comment]
@orels1 Thanks! New version works! :)

```
$ time vpm list unity
[18:53:29 INF] Found No Supported Editors
[18:53:29 INF] Found 0 Unity Installations.

╭────────────────────────┬────────────────────────────────────────────────────────────────────────╮
│ Path                   │ Unity Version                                                          │
╰────────────────────────┴────────────────────────────────────────────────────────────────────────╯
vpm list unity  0.43s user 0.08s system 9% cpu 5.466 total

$ dotnet tool update --global vrchat.vpm.cli                        
Tool 'vrchat.vpm.cli' was successfully updated from version '0.1.25' to version '0.1.26'.

$ time vpm list unity                       
[18:54:10 ERR] Unity Hub took longer than 60s to list editors
[18:54:10 INF] Found 1 Unity Installations.

╭───────────────────┬─────────────────────────────────────────────────────────────────────────────╮
│ Path              │ Unity Version                                                               │
├───────────────────┼─────────────────────────────────────────────────────────────────────────────┤
│ 2022.3.22f1       │ /Applications/Unity/Unity.app/Contents/MacOS/Unity                          │
╰───────────────────┴─────────────────────────────────────────────────────────────────────────────╯
vpm list unity  8.71s user 0.79s system 60% cpu 15.627 total
```

Minor issue: it seems that it's hard-coded to say Unity took longer than 60s when it's probably just complaining after 10 seconds.

**Comment by orels1** [comment]
Yeah that is.. odd, but thanks for confirming that it addressed the issue!

**Comment by JasonTheKitten** [comment]
@orels1 When I attempt to run the "vpm list unity" command you mentioned, it spits out an error:

```
$ vpm list unity
[14:23:04 ERR] Unity Hub took longer than 60s to list editors
[14:23:04 INF] Found No Supported Editors
[14:23:04 INF] VPM Doesn't know how to look at Linux executables for version yet, so just returning true for PathIsValidUnityVersion(/home/jason/Unity/Hub/Editor/2022.3.22f1/Editor/Unity)
[14:23:04 INF] Found 1 Unity Installations.
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at VRC.PackageManagement.CLI.Program.ListUnityEditors() in /home/runner/work/vrc-package-manager/vrc-package-manager/core/vpm-cli/Requirements.cs:line 60
   at VRC.PackageManagement.CLI.Program.<>c.<CreateListCommands>b__12_0() in /home/runner/work/vrc-package-manager/vrc-package-manager/core/vpm-cli/Program.cs:line 237
   at System.CommandLine.Handler.<>c__DisplayClass1_0.<SetHandler>b__0(InvocationContext _)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
   ```

This is on 0.1.26 with Unity 2022.3.22f1 (I also tried on 0.1.24, too).
Subsequent commands still say they can't find a supported editor.

I've tried both .NET 6 (recommended) and .NET 8 (latest)
This is on Linux 6.10.8 (the OP issue was also Linux, but I noticed a few non-Linux users in this thread)

**Comment by brilokuloj** [comment]
> @orels1 When I attempt to run the "vpm list unity" command you mentioned, it spits out an error:

I'm getting this same error on Ubuntu. I am also getting the 60s warning even though it takes 2 seconds.

**Comment by orels1** [comment]
@brilokuloj this is is an erroneous error message.
We have fixed it in the VCC and going to be releasing a new CLI version soon that addresses that

**Comment by orels1** [comment]
The other error is still on our list of things to tackle. I'll update this thread when I have any new information

**Comment by orels1** [comment]
The nullref crash mentioned by @JasonTheKitten will be addressed in the next release (which will come out together with VCC 2.4.0).
Thanks for the report!

**Comment by orels1** [comment]
The VPM CLI 0.1.28-beta.1 is up with this nullref crash fix:

```
dotnet tool install -g VRChat.VPM.CLI --version 0.1.28-beta.1
```

**Comment by Ianthasys** [comment]
Commenting to confirm that this issue is still active on version `0.1.28+4747c32ac685cdc0a1e1aef77a9d49316aa9c13a` running on Arch Linux. I installed unity 2022.3.22f1, and `vpm check hub` does succeed after adding my hub to `settings.json`, but I'm running into the similar issue of `pathToUnityExe` being emptied any time `vpm check unity` fails

**Comment by orels1** [comment]
@CanvasofSpores hmm, `pathToUnityExe` should no longer be used at all, only `unityEditors` array and `preferredEditors` dictionary should be used 🤔

**Comment by CanvasofSpores** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/100318148?v=4&amp;size=80">@CanvasofSpores](https://github.com/CanvasofSpores) hmm, `pathToUnityExe` should no longer be used at all, only `unityEditors` array and `preferredEditors` dictionary should be used 🤔

Do you have an example of what those entries should look like in the file? I've since installed my OS fresh and am starting everything with unity/vpm from scratch on linux. I've gotten it to recognize my hub installation by editing the `pathToUnityHub` entry, I'm just not sure what the entries for my install under `unityEditors` and `preferredUnityEditors` should look like

**Comment by CanvasofSpores** [comment]
So after some poking around with it, I have been able to get it to recognize my unity hub, but when running `vpm list unity`, it clears out whatever I've put into `unityEditors` or `preferredUnityEditors`


Here's my settings.json
```json
{
  "pathToUnityExe": "",
  "pathToUnityHub": "/opt/unityhub/unityhub",
  "userProjects": [],
  "unityEditors": [],
  "preferredUnityEditors": {
    "2022": "/home/canvas/Unity/Hub/Editor/2022.3.22f1/Editor/Unity"
  },
  "defaultProjectPath": "/home/canvas/.local/share/VRChatCreatorCompanion/VRChatProjects",
  "lastUIState": 0,
  "skipUnityAutoFind": false,
  "userPackageFolders": [],
  "windowSizeData": {
    "width": 0,
    "height": 0,
    "x": 0,
    "y": 0
  },
  "skipRequirements": false,
  "lastNewsUpdate": "2025-02-10T02:14:16.8199205Z",
  "allowPii": false,
  "projectBackupPath": "/home/canvas/.local/share/VRChatCreatorCompanion/ProjectBackups",
  "showPrereleasePackages": false,
  "trackCommunityRepos": true,
  "selectedProviders": 3,
  "userRepos": []
}
```

**Comment by orels1** [comment]
@CanvasofSpores 

You should run the `vpm list projects` first, since that directly invokes the DB initialization logic _before_ the editor scanning. While `vpm list unity` goes the other way.

We should just add a command to specify an editor, but for now that's how that can be done.

And yeah the preferred object is meant to look pretty much like the above:
```json
  "preferredUnityEditors": {
    "2022": "C:\\Program Files\\Unity\\Hub\\Editor\\2022.3.22f1\\Editor\\Unity.exe"
  },
```

Do you get any logs when you run `vpm list unity`?

Essentially whenever you put anything into `unityEditors` array - it goes as follows:

- It copies whatever paths there are into the database
- It then checks that all the entries in the `preferredUnityEditors` actually exist in the DB (which makes the previous step important) and removes the ones that aren't
- It then assigns any officially supported versions as preferred for the current major release (if nothing was already set)

The `vpm check unity`, however, only operates on the entries in the DB and will remove anything from the `preferredUnityEditors` that isn't included in the database

Can you check how it behaves if you run `vpm list projects` first?
I'll see if I can put together a preview version with a manual "add editor to DB, trust me, for real" command in the foreseeable future

**Comment by CanvasofSpores** [comment]
> Can you check how it behaves if you run `vpm list projects` first? I'll see if I can put together a preview version with a manual "add editor to DB, trust me, for real" command in the foreseeable future

Running `vpm list projects` seems to also be removing the entry I'd put into `preferredUnityEditors`, it doesn't seem to be creating any logs when run unfortunately. (I'd cleared out my logs folder shortly before running the command)

![Image](https://github.com/user-attachments/assets/50763f47-fa53-4699-a5ad-c4fea235aadf)

**Comment by orels1** [comment]
@CanvasofSpores sorry, I meant to do the following:

- Put your editor path into the `unityEditors` array
- Run `vpm list projects` command (to kick off DB init)
- Check what happens

It _should_ remove the entry from the `unityEditors` list and insert it into the DB followed by inserting it into the `preferredUnityEditors` (which can be left empty for this).

Last resort - you could actually just open the `vcc.liteDb` file with some liteDb editor, e.g. [OneBella](https://github.com/namigop/OneBella). And add a new entry to the `unityVersions` table by running an SQL query like this

```sql
INSERT INTO unityVersions
VALUES { "Path": "mypath", "Version": "2022.3.22f1", "LoadedFromHub": false }
```

**Comment by CanvasofSpores** [comment]
> * Put your editor path into the `unityEditors` array
> * Run `vpm list projects` command (to kick off DB init)
> * Check what happens
It seems to be also be clearing both entries in my settings.json. I'll give OneBella a try.

**Comment by CanvasofSpores** [comment]
@orels1 
> Last resort - you could actually just open the `vcc.liteDb` file with some liteDb editor, e.g. [OneBella](https://github.com/namigop/OneBella?rgh-link-date=2025-02-10T23%3A40%3A03.000Z). And add a new entry to the `unityVersions` table by running an SQL query like this
> 
> INSERT INTO unityVersions
> VALUES { "Path": "mypath", "Version": "2022.3.22f1", "LoadedFromHub": false }

I've done that with onebella (after a few hours of trying to figure out what I'm doing as I'm very much an end-user and don't know what I'm doing.), Running `vpm list projects` (after I've created a new project) does show the correct version. It does seem that running vpm check unity removes the entry from the db

**Comment by orels1** [comment]
Huh, the fact that `vpm check unity` still removes the editor despite it being manually added with `LoadedFromHub: false` is concerning.

I'll note that, ty for testing!

**Comment by HotoRas** [comment]
This should be a bug for Linux version of Unity Hub, but I should mention that Unity Hub RPM package doesn't support CLI options. It instead starts GUI interface.
Connecting the installation with VPM kinda works, but since it ignores args and starts new window, the result of `vpm check unity` is `not installed` with new Hub instance.

Video: https://youtu.be/xR0VO337spA

**Comment by orels1** [comment]
Just wanted to let everyone know that the new `0.1.29-beta.1` VPM CLI no longer performs any hub/unity checks when running common operations (unless you explicitly invoke unity-related commands)
